-- V005: IDs de catálogo (materia prima, proveedor, animal) → BIGINT autoincremental.
-- El código (codigo_*) sigue siendo VARCHAR ingresado por el usuario; unicidad solo entre activos (V003/V004).
-- Granja y Usuario mantienen VARCHAR(32) por ahora.
--
-- ATENCIÓN: borra filas que referencian estos catálogos. En dev ejecutar `make seed` o reiniciar con DevDataLoader.

DELETE FROM t_ia_prediccion_stock;
DELETE FROM t_ia_anomalia_precio;
DELETE FROM t_registro_precio;
DELETE FROM t_inventario_inicial;
DELETE FROM t_inventario;
DELETE FROM t_detalle_fabricacion;
DELETE FROM t_compra_detalle;
DELETE FROM t_compra_cabecera;
DELETE FROM t_formula_detalle;
DELETE FROM t_formula_cabecera;
DELETE FROM t_fabricacion;
DELETE FROM t_materia_prima;
DELETE FROM t_proveedor;
DELETE FROM t_animal;

-- ---------- t_materia_prima ----------
ALTER TABLE t_formula_detalle DROP CONSTRAINT IF EXISTS t_formula_detalle_id_materia_prima_fkey;
ALTER TABLE t_compra_detalle DROP CONSTRAINT IF EXISTS t_compra_detalle_id_materia_prima_fkey;
ALTER TABLE t_registro_precio DROP CONSTRAINT IF EXISTS t_registro_precio_id_materia_prima_fkey;
ALTER TABLE t_detalle_fabricacion DROP CONSTRAINT IF EXISTS t_detalle_fabricacion_id_materia_prima_fkey;
ALTER TABLE t_inventario DROP CONSTRAINT IF EXISTS t_inventario_id_materia_prima_fkey;
ALTER TABLE t_inventario_inicial DROP CONSTRAINT IF EXISTS t_inventario_inicial_id_materia_prima_fkey;
ALTER TABLE t_ia_prediccion_stock DROP CONSTRAINT IF EXISTS t_ia_prediccion_stock_id_materia_prima_fkey;
ALTER TABLE t_ia_anomalia_precio DROP CONSTRAINT IF EXISTS t_ia_anomalia_precio_id_materia_prima_fkey;

ALTER TABLE t_materia_prima DROP CONSTRAINT IF EXISTS t_materia_prima_pkey;
ALTER TABLE t_materia_prima DROP COLUMN id;
ALTER TABLE t_materia_prima ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE t_formula_detalle DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_formula_detalle ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_formula_detalle
    ADD CONSTRAINT t_formula_detalle_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id);

ALTER TABLE t_compra_detalle DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_compra_detalle ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_compra_detalle
    ADD CONSTRAINT t_compra_detalle_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id);

ALTER TABLE t_registro_precio DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_registro_precio ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_registro_precio
    ADD CONSTRAINT t_registro_precio_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id) ON DELETE CASCADE;

ALTER TABLE t_detalle_fabricacion DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_detalle_fabricacion ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_detalle_fabricacion
    ADD CONSTRAINT t_detalle_fabricacion_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id);

ALTER TABLE t_inventario DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_inventario ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_inventario
    ADD CONSTRAINT t_inventario_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id) ON DELETE CASCADE;

ALTER TABLE t_inventario_inicial DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_inventario_inicial ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_inventario_inicial
    ADD CONSTRAINT t_inventario_inicial_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id) ON DELETE CASCADE;

ALTER TABLE t_ia_prediccion_stock DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_ia_prediccion_stock ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_ia_prediccion_stock
    ADD CONSTRAINT t_ia_prediccion_stock_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id) ON DELETE CASCADE;

ALTER TABLE t_ia_anomalia_precio DROP COLUMN IF EXISTS id_materia_prima;
ALTER TABLE t_ia_anomalia_precio ADD COLUMN id_materia_prima BIGINT NOT NULL;
ALTER TABLE t_ia_anomalia_precio
    ADD CONSTRAINT t_ia_anomalia_precio_id_materia_prima_fkey
    FOREIGN KEY (id_materia_prima) REFERENCES t_materia_prima(id);

-- ---------- t_proveedor ----------
ALTER TABLE t_compra_cabecera DROP CONSTRAINT IF EXISTS t_compra_cabecera_id_proveedor_fkey;

ALTER TABLE t_proveedor DROP CONSTRAINT IF EXISTS t_proveedor_pkey;
ALTER TABLE t_proveedor DROP COLUMN id;
ALTER TABLE t_proveedor ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE t_compra_cabecera DROP COLUMN IF EXISTS id_proveedor;
ALTER TABLE t_compra_cabecera ADD COLUMN id_proveedor BIGINT NOT NULL;
ALTER TABLE t_compra_cabecera
    ADD CONSTRAINT t_compra_cabecera_id_proveedor_fkey
    FOREIGN KEY (id_proveedor) REFERENCES t_proveedor(id);

-- ---------- t_animal ----------
ALTER TABLE t_formula_cabecera DROP CONSTRAINT IF EXISTS t_formula_cabecera_id_animal_fkey;

ALTER TABLE t_animal DROP CONSTRAINT IF EXISTS t_animal_pkey;
ALTER TABLE t_animal DROP COLUMN id;
ALTER TABLE t_animal ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE t_formula_cabecera DROP COLUMN IF EXISTS id_animal;
ALTER TABLE t_formula_cabecera ADD COLUMN id_animal BIGINT NOT NULL;
ALTER TABLE t_formula_cabecera
    ADD CONSTRAINT t_formula_cabecera_id_animal_fkey
    FOREIGN KEY (id_animal) REFERENCES t_animal(id);
