-- V013: módulo Archivos — snapshots inmutables bajo demanda de Inventario/Compras/Fórmulas.
-- Un archivo es una foto de solo lectura del módulo al momento de crearlo: los datos se
-- guardan como JSONB (los DTOs de respuesta del módulo serializados) y nunca se actualizan
-- ni se borran (sin soft-delete: es un registro histórico).
-- creado_por / creado_por_email son snapshot del usuario creador (sin FK a t_usuarios:
-- el creador puede purgarse después — LimpiezaCuentasDemoService — sin romper el archivo).
-- id_granja cascadea con la granja, por lo que la purga DEMO lo cubre sin cambios.

CREATE TABLE t_archivo (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_granja        VARCHAR(32) NOT NULL REFERENCES t_granja(id) ON DELETE CASCADE,
    tipo_modulo      VARCHAR(20) NOT NULL,
    codigo_archivo   VARCHAR(50) NOT NULL,
    descripcion      VARCHAR(500),
    fecha_creacion   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    creado_por       VARCHAR(32) NOT NULL,
    creado_por_email VARCHAR(255) NOT NULL,
    total_registros  INT NOT NULL,
    datos            JSONB NOT NULL,
    CONSTRAINT uq_archivo_codigo UNIQUE (id_granja, tipo_modulo, codigo_archivo)
);

CREATE INDEX idx_archivo_granja_tipo ON t_archivo(id_granja, tipo_modulo, fecha_creacion DESC);
