-- V015: módulo Suscripciones y Pagos (Mercado Pago) — Etapa 1 (dominio).
-- t_suscripcion es la máquina de estados comercial, 1:1 con el usuario DUEÑO: al
-- activarse/expirar escribe t_usuarios.plan_suscripcion (lo que lee PlanService).
-- Una cuenta SIN fila acá es DEMO implícito (o plan asignado a mano): compatibilidad
-- con todas las cuentas existentes, sin backfill.
-- Sin ON DELETE hacia t_usuarios: la purga DEMO borra en orden explícito
-- (pagos → suscripción → empleados → dueño), ver PurgaCuentaDemoRepository.

CREATE TABLE t_suscripcion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          VARCHAR(32)   NOT NULL UNIQUE REFERENCES t_usuarios(id),
    plan                VARCHAR(20)   NOT NULL, -- plan contratado: STARTER | BUSINESS | ENTERPRISE
    periodo             VARCHAR(10)   NOT NULL, -- MENSUAL | ANUAL
    estado              VARCHAR(20)   NOT NULL, -- PENDIENTE_PAGO | ACTIVA | CANCELADA | EXPIRADA
    precio_ars          NUMERIC(12,2) NOT NULL, -- snapshot del precio al contratar (RD-P12)
    fecha_inicio        TIMESTAMPTZ   NOT NULL,
    fecha_fin_periodo   TIMESTAMPTZ,            -- "pagado hasta"; NULL mientras PENDIENTE_PAGO
    plan_pendiente      VARCHAR(20),            -- downgrade programado (incl. DEMO); NULL = ninguno
    periodo_pendiente   VARCHAR(10),
    mp_preapproval_id   VARCHAR(64) UNIQUE,     -- NULL en modo simulado
    ultimo_cobro_estado VARCHAR(20),            -- APROBADO | RECHAZADO | PENDIENTE (gracia RD-P8)
    ultimo_cobro_fecha  TIMESTAMPTZ,
    fecha_creacion      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Historial de cobros de una suscripción. mp_payment_id es la clave de idempotencia del
-- webhook (RD-P9): un mismo pago notificado dos veces no genera dos filas.
CREATE TABLE t_pago (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_suscripcion BIGINT        NOT NULL REFERENCES t_suscripcion(id),
    mp_payment_id  VARCHAR(64) UNIQUE,          -- NULL en modo simulado
    monto_ars      NUMERIC(12,2) NOT NULL,
    estado         VARCHAR(20)   NOT NULL,      -- APROBADO | RECHAZADO | PENDIENTE | DEVUELTO
    descripcion    VARCHAR(200),                -- "REFORMA - Plan BUSINESS (Mensual)"
    fecha_pago     TIMESTAMPTZ   NOT NULL
);
CREATE INDEX idx_pago_suscripcion ON t_pago (id_suscripcion, fecha_pago DESC);

-- RD-P7: base de cálculo de la purga DEMO. La setea el registro y toda caída del plan
-- efectivo a DEMO (lógica de Etapa 2); mientras tanto la purga usará
-- COALESCE(fecha_inicio_demo, fecha_registro), así las filas nuevas sin valor no cambian
-- el comportamiento actual. Backfill: las cuentas DEMO existentes arrancan su ventana
-- desde el registro, igual que hoy.
ALTER TABLE t_usuarios ADD COLUMN fecha_inicio_demo TIMESTAMPTZ;
UPDATE t_usuarios SET fecha_inicio_demo = fecha_registro WHERE plan_suscripcion = 'DEMO';
